### ISSUE TITLE
Transition requires 6 arguments

### ISSUE THREAD

**Issue by abelfleitas** [Banane9/StateMachine#1]
In the example and documentation, Transition is shown with 5 param (Transition<ExampleStateMachine, ExampleStates, TStateIn, string, TStateOut>)
when I try to use it asks me for 6 parameters, I have not figured out how to use it.

Transition<TMachine, TStates, TStateIn, TWith, TStateOut, TTransitionAttempt>

![2022-03-06_043824](https://tlgur.com/d/gpYbPe14)

**Comment by Banane9** [comment]
Hello, you're using an old version, the current version doesn't have that parameter anymore.

**Comment by abelfleitas** [comment]
OK I was using version 1.0.12 it was the one I found on nuget
